#!/bin/bash

# To uninstall, run the two following commands
# brew uninstall sketchybar
# brew untap FelixKratz/formulae


source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT="SF Pro"

# aerospace setting
AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')


##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  position=top
  height=37
  blur_radius=30
  sticky=off
  padding_left=10
  padding_right=10
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  border_color=0x00000000
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  updates=when_shown
  padding_left=5
  padding_right=5
  # icon.font="Hack Nerd Font:Bold:17.0"
  icon.font="$FONT:Semibold:14.0"
  # label.font="Hack Nerd Font:Bold:14.0"
  label.font="$FONT:Semibold:15.0"
  icon.color=$ITEM_FG_COLOR
  label.color=$ITEM_FG_COLOR
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=10
  background.color=$ITEM_BG_COLOR
  background.corner_radius=9
  background.height=26
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.background.shadow_drawing=on
  popup.blur_radius=20
  scroll_texts=on
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
# source $ITEM_DIR/battery.sh # uncomment this if on a laptop
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/vpn.sh
source $ITEM_DIR/mic.sh
source $ITEM_DIR/reminders.sh
source $ITEM_DIR/weather.sh

sketchybar --hotload off

##### Finalizing Setup #####
##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
